version: '3'

services:
  app:
    build: .
    ports:
      - "4321:4321"
    environment:
      PORT: "4321"
      MONGO_URI: "mongodb+srv://valet-demo:kXlI1nGFx7AfjLbz@sandbox-egjgq.gcp.mongodb.net"
      MONGO_DB: "valet-demo"
      TMP_DIR: "/ml/images"
      ML_HOST: "ml"
      ML_PORT: "5000"
    volumes:
      - image-data:/ml/images

  ml:
    build: ./ml
    volumes:
      - image-data:/ml/images

volumes:
  image-data:
