version: '3'

services:
  app:
    depends_on:
      - database
    build: .
    ports:
      - "4321:4321"
    environment:
      MONGO_URI: "mongodb://admin:password@localhost"
      MONGO_DB: "valet-demo"
    volumes:
      - image-data:/ml/images

  ml:
    depends_on:
      - database
    build: ./ml
    volumes:
      - image-data:/images

volumes:
  image-data:
